#!/bin/bash

# Script pour mettre à jour les IPs dans les fichiers de configuration
# Usage: ./update-config.sh <EC2_PUBLIC_IP>

EC2_IP=$1

if [ -z "$EC2_IP" ]; then
  echo "Error: EC2 IP address is required"
  echo "Usage: $0 <EC2_PUBLIC_IP>"
  exit 1
fi

echo "🔧 Updating configuration files with EC2 IP: $EC2_IP"

# 1. Mettre à jour backend/config.json
BACKEND_CONFIG="./backend/config.json"
if [ -f "$BACKEND_CONFIG" ]; then
  echo "📝 Updating $BACKEND_CONFIG..."
  # Utiliser jq si disponible, sinon sed
  if command -v jq &> /dev/null; then
    jq --arg ip "$EC2_IP" '.database.remote.host = $ip' "$BACKEND_CONFIG" > "$BACKEND_CONFIG.tmp" && mv "$BACKEND_CONFIG.tmp" "$BACKEND_CONFIG"
  else
    sed -i.bak "s/\"host\": \"YOUR_EC2_IP_HERE\"/\"host\": \"$EC2_IP\"/g" "$BACKEND_CONFIG"
    sed -i.bak "s/\"host\": \"[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\"/\"host\": \"$EC2_IP\"/g" "$BACKEND_CONFIG"
    rm -f "$BACKEND_CONFIG.bak"
  fi
  echo "Backend config updated"
else
  echo "Warning: $BACKEND_CONFIG not found"
fi

# 2. Mettre à jour frontend/public/config.js
FRONTEND_CONFIG="./frontend/public/config.js"
if [ -f "$FRONTEND_CONFIG" ]; then
  echo "📝 Updating $FRONTEND_CONFIG..."
  cat > "$FRONTEND_CONFIG" << EOF
window.ENV_CONFIG = {
  VITE_API_URL: 'http://${EC2_IP}:3001',
};
EOF
  echo "Frontend config updated"
else
  echo "Warning: $FRONTEND_CONFIG not found"
fi

# 3. Mettre à jour docker-compose.yml si nécessaire
DOCKER_COMPOSE="./docker-compose.yml"
if [ -f "$DOCKER_COMPOSE" ]; then
  echo "📝 Checking $DOCKER_COMPOSE..."
  # Remplacer l'IP dans les variables d'environnement si présentes
  sed -i.bak "s/EC2_IP=.*/EC2_IP=$EC2_IP/g" "$DOCKER_COMPOSE"
  rm -f "$DOCKER_COMPOSE.bak"
  echo "Docker compose checked"
else
  echo "Warning: $DOCKER_COMPOSE not found"
fi

# 4. Créer un fichier .env avec les valeurs
ENV_FILE="./.env"
echo "📝 Creating/updating $ENV_FILE..."
cat > "$ENV_FILE" << EOF
# Generated by Terraform
EC2_PUBLIC_IP=$EC2_IP
BACKEND_URL=http://${EC2_IP}:3001
FRONTEND_URL=http://${EC2_IP}:5173
DB_HOST=$EC2_IP
DB_PORT=5432
EOF
echo ".env file created"

echo ""
echo "✨ Configuration update complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EC2 Public IP: $EC2_IP"
echo "Backend API:   http://${EC2_IP}:3001"
echo "Frontend:      http://${EC2_IP}:5173"
echo "PostgreSQL:    ${EC2_IP}:5432"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
