name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Give the workflow explicit permissions so GITHUB_TOKEN can push to GHCR
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    name: Build and push images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    outputs:
      docker_tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create short tag from commit
        id: set-tag
        run: echo "tag=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        env:
          SHORT_HASH: ${{ steps.set-tag.outputs.tag }}
          REPO_OWNER: ${{ env.OWNER }}
        run: |
          SERVICE=${{ matrix.service }}
          # lowercase the owner (GHCR usernames are case-insensitive but using lowercase keeps tags tidy)
          REPO_OWNER=$(echo "${REPO_OWNER}" | tr '[:upper:]' '[:lower:]')
          IMAGE=${{ env.REGISTRY }}/${REPO_OWNER}/${SERVICE}:${SHORT_HASH}
          echo "Building $IMAGE"
          # Build using the service directory as build context and the right Dockerfile
          docker build -f ${SERVICE}/Dockerfile -t $IMAGE ${SERVICE}
          echo "Pushing $IMAGE"
          docker push $IMAGE

  terraform-deploy:
    name: Deploy infrastructure with Terraform
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create short tag from commit
        id: set-tag
        run: echo "tag=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_github_username: ${{ secrets.TF_VAR_GITHUB_USERNAME }}
          TF_VAR_github_token: ${{ secrets.GHCR_PAT }}
          TF_VAR_docker_tag: ${{ steps.set-tag.outputs.tag }}
        run: |
          terraform plan \
            -var="docker_tag=${{ steps.set-tag.outputs.tag }}" \
            -var="github_username=${{ secrets.TF_VAR_GITHUB_USERNAME }}" \
            -var="github_token=${{ secrets.GHCR_PAT }}" \
            -out=tfplan

      - name: Terraform Apply
        env:
          TF_VAR_github_username: ${{ secrets.TF_VAR_GITHUB_USERNAME }}
          TF_VAR_github_token: ${{ secrets.GHCR_PAT }}
          TF_VAR_docker_tag: ${{ steps.set-tag.outputs.tag }}
        run: terraform apply -auto-approve tfplan

      - name: Output Infrastructure Info
        run: |
          echo "=== Infrastructure Deployed ==="
          terraform output application_summary

